name: Sigma Engine Build
on: [push]

jobs:
  android_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install Android NDK
        run: |
          echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;25.2.9519653"

      - name: Install Fyne-cross
        run: go install fyne.io/fyne-cross@latest

      - name: Build APK
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          fyne-cross android -app-id com.sigma.engine -release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Sigma-Engine-APK
          path: fyne-cross/dist/android/*.apk
          
