name: Sigma Engine Build
on: [push]

jobs:
  android_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev xorg-dev
          go mod tidy

      - name: Build APK
        uses: lucor/fyne-cross-action@v1
        with:
          target: android
          app-id: com.sigma.engine
          release: false

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Sigma-Engine-APK
          path: fyne-cross/dist/android/*.apk
          
